# Generated by Django 4.2.16 on 2026-06-20 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("brand", models.CharField(max_length=80)),
                (
                    "cost_per_ml",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("max_size", models.CharField(default="10ml", max_length=8)),
                (
                    "published_tier",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("current_inventory", models.IntegerField(default=0)),
                ("lab_qty", models.IntegerField(default=0)),
                ("wh_qty", models.IntegerField(default=0)),
                ("avg_window_inventory", models.FloatField(default=0)),
                ("liquid_opened_date", models.DateField(blank=True, null=True)),
                ("is_new", models.BooleanField(default=False)),
                ("created_at", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticsResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateField()),
                ("weighted_daily_sales", models.FloatField(default=0)),
                ("velocity", models.FloatField(default=0)),
                ("days_of_inventory", models.FloatField(default=0)),
                ("roi", models.FloatField(default=0)),
                ("inventory_value", models.FloatField(default=0)),
                ("liquid_age_days", models.IntegerField(blank=True, null=True)),
                ("sell_through_rate", models.FloatField(default=0)),
                ("portfolio_score", models.FloatField(default=0)),
                ("portfolio_rank", models.IntegerField(default=0)),
                ("category", models.CharField(default="Standard", max_length=40)),
                (
                    "category_reason",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("lifecycle_tier", models.CharField(default="CORE", max_length=16)),
                (
                    "liquidation_strategy",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("discount_pct", models.IntegerField(default=0)),
                ("naive_sell_through", models.FloatField(default=0)),
                ("sales_norm", models.FloatField(default=0)),
                ("profit_norm", models.FloatField(default=0)),
                ("roi_norm", models.FloatField(default=0)),
                ("score_balanced", models.FloatField(default=0)),
                ("is_pareto_optimal", models.BooleanField(default=False)),
                ("v1_rank", models.IntegerField(default=0)),
                ("v1_verdict", models.CharField(default="", max_length=40)),
                (
                    "expected_tier",
                    models.CharField(blank=True, default="", max_length=4),
                ),
                ("published_price", models.FloatField(default=0)),
                ("correct_price", models.FloatField(default=0)),
                ("mispriced", models.BooleanField(default=False)),
                (
                    "mispricing_severity",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["portfolio_rank"],
            },
        ),
        migrations.CreateModel(
            name="DailySale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("units", models.IntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["product", "date"],
                        name="core_dailys_product_bf7aab_idx",
                    )
                ],
                "unique_together": {("product", "date")},
            },
        ),
    ]
