# Generated by Django 4.2.16 on 2026-06-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateField()),
                ("stock", models.IntegerField(default=0)),
                ("daily_sales", models.FloatField(default=0)),
                ("days_supply", models.IntegerField(default=0)),
                ("total_profit", models.FloatField(default=0)),
                ("roi_pct", models.FloatField(default=0)),
                ("score", models.FloatField(default=0)),
                ("is_pareto", models.BooleanField(default=False)),
                ("status", models.CharField(default="Optimize", max_length=12)),
                ("profit_per_day", models.FloatField(default=0)),
                ("sell_through_pct", models.FloatField(default=0)),
                ("reorder_point", models.IntegerField(default=0)),
                ("eoq", models.IntegerField(default=0)),
                ("safety_stock", models.IntegerField(default=0)),
                ("days_of_inventory", models.IntegerField(default=0)),
                ("growth_rate_pct", models.FloatField(default=0)),
                ("suggested_qty", models.IntegerField(default=0)),
                ("inventory_turnover", models.FloatField(default=0)),
                ("sales_norm", models.FloatField(default=0)),
                ("profit_norm", models.FloatField(default=0)),
                ("roi_norm", models.FloatField(default=0)),
                ("sell_through_norm", models.FloatField(default=0)),
                ("turnover_norm", models.FloatField(default=0)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="v1stats",
                        to="core.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
    ]
