"""
A list of well-known retail fragrances used to make the synthetic catalog look
realistic (a decant shop sells 1ml samples of these). These are public product
names only — all sales, inventory, cost, and pricing numbers are fabricated.

Each entry: (brand, line, concentration, audience).
"""
FRAGRANCES = [
    ("Creed", "Aventus", "Eau de Parfum", "for Men"),
    ("Creed", "Green Irish Tweed", "Eau de Parfum", "for Men"),
    ("Creed", "Silver Mountain Water", "Eau de Parfum", "Unisex"),
    ("Creed", "Royal Oud", "Eau de Parfum", "Unisex"),
    ("Creed", "Viking", "Eau de Parfum", "for Men"),
    ("Tom Ford", "Tobacco Oud", "Eau de Parfum", "Unisex"),
    ("Tom Ford", "Oud Wood", "Eau de Parfum", "Unisex"),
    ("Tom Ford", "Tobacco Vanille", "Eau de Parfum", "Unisex"),
    ("Tom Ford", "Beau de Jour", "Eau de Parfum", "for Men"),
    ("Tom Ford", "Ombre Leather", "Eau de Parfum", "Unisex"),
    ("Tom Ford", "Lost Cherry", "Eau de Parfum", "Unisex"),
    ("Tom Ford", "Bitter Peach", "Eau de Parfum", "Unisex"),
    ("Tom Ford", "Soleil Blanc", "Eau de Parfum", "Unisex"),
    ("Parfums de Marly", "Layton", "Eau de Parfum", "for Men"),
    ("Parfums de Marly", "Althair", "Eau de Parfum", "for Men"),
    ("Parfums de Marly", "Pegasus", "Eau de Parfum", "for Men"),
    ("Parfums de Marly", "Herod", "Eau de Parfum", "for Men"),
    ("Parfums de Marly", "Carlisle", "Eau de Parfum", "Unisex"),
    ("Parfums de Marly", "Greenley", "Eau de Parfum", "for Men"),
    ("Parfums de Marly", "Delina", "Eau de Parfum", "for Women"),
    ("Maison Francis Kurkdjian", "Baccarat Rouge 540", "Eau de Parfum", "Unisex"),
    ("Maison Francis Kurkdjian", "Baccarat Rouge 540", "Extrait de Parfum", "Unisex"),
    ("Maison Francis Kurkdjian", "Grand Soir", "Eau de Parfum", "Unisex"),
    ("Maison Francis Kurkdjian", "Oud Satin Mood", "Eau de Parfum", "Unisex"),
    ("Maison Francis Kurkdjian", "Gentle Fluidity Gold", "Eau de Parfum", "Unisex"),
    ("Dior", "Sauvage", "Eau de Toilette", "for Men"),
    ("Dior", "Sauvage Elixir", "Parfum", "for Men"),
    ("Dior", "Homme Intense", "Eau de Parfum", "for Men"),
    ("Dior", "Fahrenheit", "Eau de Toilette", "for Men"),
    ("Dior", "Ambre Nuit", "Eau de Parfum", "Unisex"),
    ("Yves Saint Laurent", "Y", "Eau de Parfum", "for Men"),
    ("Yves Saint Laurent", "Myslf", "Eau de Parfum", "for Men"),
    ("Yves Saint Laurent", "La Nuit de L'Homme", "Eau de Toilette", "for Men"),
    ("Jean Paul Gaultier", "Le Male", "Eau de Toilette", "for Men"),
    ("Jean Paul Gaultier", "Le Male Le Parfum", "Eau de Parfum", "for Men"),
    ("Jean Paul Gaultier", "Ultra Male", "Eau de Toilette", "for Men"),
    ("Xerjoff", "Naxos", "Eau de Parfum", "Unisex"),
    ("Xerjoff", "Erba Pura", "Eau de Parfum", "Unisex"),
    ("Xerjoff", "Alexandria II", "Parfum", "Unisex"),
    ("Xerjoff", "More Than Words", "Eau de Parfum", "Unisex"),
    ("Amouage", "Reflection Man", "Eau de Parfum", "for Men"),
    ("Amouage", "Interlude Man", "Eau de Parfum", "for Men"),
    ("Amouage", "Jubilation XXV", "Eau de Parfum", "for Men"),
    ("Sospiro", "Vibrato", "Eau de Parfum", "Unisex"),
    ("Initio", "Oud for Greatness", "Eau de Parfum", "Unisex"),
    ("Initio", "Side Effect", "Eau de Parfum", "Unisex"),
    ("Nishane", "Hacivat", "Extrait de Parfum", "Unisex"),
    ("Nishane", "Ani", "Extrait de Parfum", "Unisex"),
    ("Mancera", "Cedrat Boise", "Eau de Parfum", "Unisex"),
    ("Mancera", "Red Tobacco", "Eau de Parfum", "Unisex"),
    ("Montale", "Arabians Tonka", "Eau de Parfum", "Unisex"),
    ("Montale", "Intense Cafe", "Eau de Parfum", "Unisex"),
    ("Versace", "Eros", "Eau de Toilette", "for Men"),
    ("Versace", "Eros Flame", "Eau de Parfum", "for Men"),
    ("Versace", "Dylan Blue", "Eau de Toilette", "for Men"),
    ("Giorgio Armani", "Acqua di Gio", "Eau de Toilette", "for Men"),
    ("Giorgio Armani", "Acqua di Gio Profumo", "Parfum", "for Men"),
    ("Giorgio Armani", "Stronger With You", "Eau de Toilette", "for Men"),
    ("Givenchy", "Gentleman", "Eau de Parfum", "for Men"),
    ("Givenchy", "Gentleman Intense", "Eau de Parfum", "for Men"),
    ("Azzaro", "The Most Wanted", "Eau de Parfum", "for Men"),
    ("Azzaro", "Wanted by Night", "Eau de Parfum", "for Men"),
    ("Chanel", "Bleu de Chanel", "Eau de Parfum", "for Men"),
    ("Chanel", "Allure Homme Sport", "Eau de Toilette", "for Men"),
    ("Chanel", "Coco Mademoiselle", "Eau de Parfum", "for Women"),
    ("Paco Rabanne", "1 Million", "Eau de Toilette", "for Men"),
    ("Paco Rabanne", "Invictus", "Eau de Toilette", "for Men"),
    ("Paco Rabanne", "Phantom", "Eau de Toilette", "for Men"),
    ("Bvlgari", "Man in Black", "Eau de Parfum", "for Men"),
    ("Lattafa", "Khamrah", "Eau de Parfum", "Unisex"),
    ("Lattafa", "Asad", "Eau de Parfum", "for Men"),
    ("Lattafa", "Yara", "Eau de Parfum", "for Women"),
    ("Byredo", "Gypsy Water", "Eau de Parfum", "Unisex"),
    ("Byredo", "Bal d'Afrique", "Eau de Parfum", "Unisex"),
    ("Le Labo", "Santal 33", "Eau de Parfum", "Unisex"),
    ("Le Labo", "Another 13", "Eau de Parfum", "Unisex"),
    ("Kilian", "Black Phantom", "Eau de Parfum", "Unisex"),
    ("Kilian", "Angels' Share", "Eau de Parfum", "Unisex"),
    ("Roja", "Elysium", "Parfum", "for Men"),
    ("Roja", "Enigma", "Parfum", "for Men"),
    ("Frederic Malle", "Portrait of a Lady", "Eau de Parfum", "for Women"),
    ("Frederic Malle", "Musc Ravageur", "Eau de Parfum", "Unisex"),
    ("Mugler", "Alien", "Eau de Parfum", "for Women"),
    ("Mugler", "Angel", "Eau de Parfum", "for Women"),
    ("Carolina Herrera", "Good Girl", "Eau de Parfum", "for Women"),
    ("Carolina Herrera", "Bad Boy", "Eau de Toilette", "for Men"),
    ("Viktor & Rolf", "Spicebomb Extreme", "Eau de Parfum", "for Men"),
    ("Viktor & Rolf", "Flowerbomb", "Eau de Parfum", "for Women"),
    ("Prada", "Luna Rossa Carbon", "Eau de Toilette", "for Men"),
]
