# Generated by Django 4.2.16 on 2026-06-21 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("created_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="COMPLETED",
                        max_length=12,
                    ),
                ),
                ("marketplace", models.CharField(default="Marketplace", max_length=40)),
            ],
            options={
                "ordering": ["-created_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variant_sku", models.CharField(max_length=96, unique=True)),
                ("bottle_type", models.CharField(max_length=16)),
                ("size", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("POSTED", "Posted"),
                            ("PENDING", "Pending"),
                            ("FAILED", "Failed"),
                        ],
                        default="POSTED",
                        max_length=8,
                    ),
                ),
                (
                    "failed_reason",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("posted_on", models.DateField(blank=True, null=True)),
                (
                    "base_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="core.product",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="automation.postingjob",
                    ),
                ),
            ],
            options={
                "ordering": ["job_id", "variant_sku"],
            },
        ),
    ]
